######################################################################
# Automatically generated by qmake (2.01a) ?? 19. ??? 21:45:41 2008
######################################################################

TEMPLATE = app
TARGET = tst
DESTDIR = ./
QT += core gui widgets

# Input
SOURCES += AeroButton.cpp
HEADERS += AeroButton.h

SOURCES += main.cpp

DEPENDPATH += .
INCLUDEPATH += .

include(./stdconfig.pri)
